eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://payment-service/payment/createPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://order-service/order/createOrder
